name: GymGuru
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  
  mailer: ^6.0.0

  cupertino_icons: ^1.0.8
  flutter_email_sender: ^7.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LOGO.jpg"


flutter:

  uses-material-design: true

  assets:
    - assets/images/LOGO.jpg
    - assets/images/iconepng.png
    - assets/images/icone2png.png
    - assets/images/FotoCaio.png
  fonts:
    - family: BreeSerif
      fonts:
        - asset: assets/fonts/BreeSerif-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
